name: Continuous Integration
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install dependencies
        run: bundle install
      - name: Run Rubocop
        run: bundle exec rubocop
